version: '3.7'

services:
  hesai-ready:
    container_name: ublox-rtk-ros2-node-container
    image: ipbalfredo/rtk-node:humble
    restart: always
    privileged: true
    network_mode: "host" # Use host network mode
    ports:
      - "8084:8084"
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/app:rw
      - /dev:/dev:ro
    stdin_open: true
    tty: true
